"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { changeAdminPassword, createAdminUser, listAdminUsers, loginAdmin, logoutAdmin, validateAdminSession, type AdminIdentity, type AdminUser } from "@/lib/admin-auth";
import { createCloudPlaylist, createCloudSchedule, createCloudTv, deleteCloudMedia, fetchCloudData, updateCloudTvPlaylist, uploadCloudMedia } from "@/lib/cloud-data";
import { Activity, BarChart3, Bell, CalendarClock, CheckCircle2, ChevronRight, CloudUpload, FileImage, Film, FolderOpen, HardDrive, KeyRound, LayoutDashboard, ListVideo, LogOut, Megaphone, Monitor, Plus, Search, Settings, ShieldCheck, Sparkles, Tv, UserPlus, Users, Wifi, WifiOff, X, Zap } from "lucide-react";
import { toast, Toaster } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarRail, SidebarTrigger } from "@/components/ui/sidebar";

type Media={id:number;name:string;mimeType:string;size:number;category:string;status:string;createdAt:string;storagePath:string;url:string};
type Device={id:number;name:string;code:string;unit:string;location:string;resolution:string;orientation:string;status:string;playlistId:number|null;lastSeen:string|null;publicToken:string};
type Playlist={id:number;name:string;status:string;itemCount:number;createdAt:string;mediaIds?:number[]};
type Schedule={id:number;name:string;playlistId:number;startsAt:string;endsAt:string|null;status:string};
type Data={media:Media[];tvs:Device[];playlists:Playlist[];schedules:Schedule[]};
const nav=[["overview","Visão geral",LayoutDashboard],["contents","Conteúdos",FolderOpen],["playlists","Playlists",ListVideo],["schedules","Programações",CalendarClock],["campaigns","Campanhas",Megaphone],["tvs","TVs e dispositivos",Monitor],["layouts","Modelos de tela",Sparkles],["reports","Relatórios",BarChart3],["users","Usuários e permissões",Users],["settings","Configurações",Settings]] as const;
const titles:Record<string,[string,string]>={overview:["Visão geral","Acompanhe toda a operação das TVs em tempo real."],contents:["Biblioteca de conteúdos","Envie, organize e prepare mídias para exibição."],playlists:["Playlists","Monte sequências de reprodução para suas telas."],schedules:["Programações","Defina quando cada playlist deve entrar no ar."],campaigns:["Campanhas","Agrupe anúncios e comunicações por objetivo."],tvs:["TVs e dispositivos","Cadastre, vincule e monitore todos os players."],layouts:["Modelos de tela","Organize conteúdos em layouts corporativos."],reports:["Relatórios","Acompanhe exibições, disponibilidade e desempenho."],users:["Usuários e permissões","Controle o acesso da equipe ao painel."],settings:["Configurações","Personalize identidade, reprodução e preferências."]};
function bytes(v:number){if(!v)return"0 MB";const u=["B","KB","MB","GB","TB"],i=Math.floor(Math.log(v)/Math.log(1024));return`${(v/1024**i).toFixed(i>1?1:0)} ${u[i]}`}

export default function Home(){
 const[section,setSection]=useState("overview"),[data,setData]=useState<Data>({media:[],tvs:[],playlists:[],schedules:[]}),[loading,setLoading]=useState(true),[search,setSearch]=useState("");
 const[modal,setModal]=useState<"upload"|"tv"|"playlist"|"schedule"|null>(null),[uploading,setUploading]=useState<Record<string,number>>({});
 const[adminSession,setAdminSession]=useState<AdminIdentity|null>(null),[authLoading,setAuthLoading]=useState(true);
 const load=useCallback(async()=>{try{setData(await fetchCloudData() as Data)}catch(error){console.error(error);toast.error("Não foi possível carregar os dados do Supabase.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void validateAdminSession().then(setAdminSession).finally(()=>setAuthLoading(false))},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{
  type Context={registerTool:(tool:Record<string,unknown>,options?:{signal?:AbortSignal})=>void|Promise<void>};
  const context=(document as Document&{modelContext?:Context}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  void Promise.resolve(context.registerTool({name:"start_content_upload",title:"Adicionar conteúdo",description:"Abre a biblioteca e prepara o envio de um novo vídeo ou imagem.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{setSection("contents");setModal("upload");return{status:"ready",view:"contents"}}},{signal:lifecycle.signal})).catch(()=>{});
  return()=>lifecycle.abort();
 },[]);
 const filtered=useMemo(()=>data.media.filter(m=>m.name.toLowerCase().includes(search.toLowerCase())||m.category.toLowerCase().includes(search.toLowerCase())),[data.media,search]);
 const online=data.tvs.filter(t=>t.status==="online").length,storage=data.media.reduce((s,m)=>s+m.size,0);
 async function action(payload:Record<string,unknown>){if(payload.action==="create-tv")await createCloudTv(payload);if(payload.action==="update-tv-playlist")await updateCloudTvPlaylist(Number(payload.id),payload.playlistId?Number(payload.playlistId):null);if(payload.action==="create-playlist")await createCloudPlaylist(String(payload.name),(payload.mediaIds as number[])||[]);if(payload.action==="create-schedule")await createCloudSchedule(payload);if(payload.action==="delete-media")await deleteCloudMedia(Number(payload.id));await load();return{ok:true}}
 async function uploadFiles(files:FileList|File[]){setModal(null);for(const file of Array.from(files)){try{setUploading(v=>({...v,[file.name]:1}));await uploadCloudMedia(file,progress=>setUploading(v=>({...v,[file.name]:progress})));toast.success(`${file.name} enviado para a nuvem`)}catch(error){console.error(error);toast.error(`Falha ao enviar ${file.name}`)}finally{setUploading(v=>{const n={...v};delete n[file.name];return n})}}await load()}
 function jump(s:string,m?:typeof modal){setSection(s);if(m)setModal(m)}
 if(authLoading)return <AuthShell><div className="text-center"><div className="mx-auto mb-4 size-9 animate-spin rounded-full border-4 border-slate-200 border-t-emerald-500"/><p className="text-sm text-slate-500">Verificando acesso...</p></div></AuthShell>;
 if(!adminSession)return <AdminLogin onLogin={setAdminSession}/>;
 if(adminSession.mustChangePassword)return <ChangePassword username={adminSession.username} onChanged={()=>setAdminSession({...adminSession,mustChangePassword:false})}/>;
 return <SidebarProvider style={{"--sidebar-width":"17rem"} as React.CSSProperties}>
  <Sidebar collapsible="icon" className="border-r-0 bg-[#07172c] text-white"><SidebarHeader className="border-b border-white/10 p-4"><div className="flex items-center gap-3 overflow-hidden"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-400 text-[#07172c]"><Tv className="size-5"/></div><div className="min-w-0"><div className="truncate font-bold">TV Corporativa</div><div className="truncate text-xs text-slate-400">Central de conteúdo</div></div></div></SidebarHeader>
   <SidebarContent className="px-2 py-3"><SidebarGroup><SidebarGroupLabel className="text-slate-500">GESTÃO</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={section===id} tooltip={label} onClick={()=>setSection(id)} className="h-10 text-slate-300 hover:bg-white/8 hover:text-white data-[active=true]:bg-emerald-400/14 data-[active=true]:text-emerald-300"><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent>
   <SidebarFooter className="border-t border-white/10 p-3"><a href="/tv" target="_blank" className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-slate-300 hover:bg-white/10"><div className="grid size-8 place-items-center rounded-lg bg-emerald-400/15 text-emerald-300"><Monitor className="size-4"/></div><span className="truncate">Abrir modo TV</span><ChevronRight className="ml-auto size-4"/></a></SidebarFooter><SidebarRail/>
  </Sidebar>
  <SidebarInset className="min-w-0 bg-[#f5f7fb]"><header className="sticky top-0 z-20 flex h-17 items-center gap-3 border-b border-slate-200/80 bg-white/85 px-4 backdrop-blur-xl md:px-7"><SidebarTrigger className="size-9"/><div className="relative max-w-lg flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar conteúdos, TVs e campanhas" className="h-10 border-0 bg-slate-100/80 pl-10 shadow-none"/></div><Button variant="ghost" size="icon" className="relative rounded-full"><Bell/><span className="absolute right-2 top-2 size-2 rounded-full bg-amber-400 ring-2 ring-white"/></Button><div className="hidden items-center gap-3 sm:flex"><div className="grid size-9 place-items-center rounded-full bg-[#0b2343] text-xs font-bold uppercase text-white">{adminSession.username.slice(0,2)}</div><div className="hidden lg:block"><p className="text-sm font-semibold">{adminSession.username}</p><p className="text-xs text-slate-500">Administrador</p></div></div><Button variant="ghost" size="icon" aria-label="Sair" title="Sair" onClick={()=>void logoutAdmin().finally(()=>setAdminSession(null))}><LogOut className="size-4"/></Button></header>
   <main className="mx-auto w-full max-w-[1500px] p-4 md:p-7 lg:p-8"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-emerald-600"><span className="size-1.5 rounded-full bg-emerald-500"/>Central de operação</div><h1 className="text-2xl font-bold tracking-tight text-slate-950 md:text-3xl">{titles[section][0]}</h1><p className="mt-1 text-sm text-slate-500">{titles[section][1]}</p></div><div>{section==="contents"&&<TopButton onClick={()=>setModal("upload")}>Adicionar conteúdo</TopButton>}{section==="playlists"&&<TopButton onClick={()=>setModal("playlist")}>Criar playlist</TopButton>}{section==="schedules"&&<TopButton onClick={()=>setModal("schedule")}>Criar programação</TopButton>}{section==="tvs"&&<TopButton onClick={()=>setModal("tv")}>Cadastrar TV</TopButton>}</div></div>
    {section==="overview"&&<Overview data={data} loading={loading} online={online} storage={storage} jump={jump}/>} {section==="contents"&&<Contents items={filtered} uploading={uploading} search={search} onUpload={uploadFiles} onDelete={async id=>{await action({action:"delete-media",id});toast.success("Conteúdo removido")}}/>} {section==="playlists"&&<Playlists items={data.playlists} onCreate={()=>setModal("playlist")}/>} {section==="schedules"&&<Schedules items={data.schedules} playlists={data.playlists} onCreate={()=>setModal("schedule")}/>} {section==="tvs"&&<Devices items={data.tvs} playlists={data.playlists} onCreate={()=>setModal("tv")} onPlaylistChange={async(id,playlistId)=>{await action({action:"update-tv-playlist",id,playlistId});toast.success("Playlist da TV atualizada")}}/>} {section==="users"&&<AdminUsers/>} {!['overview','contents','playlists','schedules','tvs','users'].includes(section)&&<ComingSoon section={section}/>} 
   </main></SidebarInset>
  <UploadDialog open={modal==="upload"} close={()=>setModal(null)} onUpload={uploadFiles}/><TvDialog open={modal==="tv"} close={()=>setModal(null)} playlists={data.playlists} onSave={async p=>{await action({action:"create-tv",...p});setModal(null);toast.success("TV cadastrada")}}/><PlaylistDialog open={modal==="playlist"} close={()=>setModal(null)} media={data.media} onSave={async p=>{await action({action:"create-playlist",...p});setModal(null);toast.success("Playlist criada")}}/><ScheduleDialog open={modal==="schedule"} close={()=>setModal(null)} playlists={data.playlists} onSave={async p=>{await action({action:"create-schedule",...p});setModal(null);toast.success("Programação criada")}}/><Toaster richColors position="top-right"/>
 </SidebarProvider>
}
function AuthShell({children}:{children:React.ReactNode}){return <main className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_top,#12395f,#07172c_65%)] p-4"><Card className="w-full max-w-md border-white/10 bg-white shadow-2xl"><CardHeader className="text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-emerald-400 text-[#07172c]"><Tv/></div><CardTitle className="mt-3 text-2xl">TV Corporativa</CardTitle><CardDescription>Painel administrativo SDE</CardDescription></CardHeader><CardContent>{children}</CardContent></Card></main>}
function AdminLogin({onLogin}:{onLogin:(admin:AdminIdentity)=>void}){const[username,setUsername]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{onLogin(await loginAdmin(username,password))}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível entrar.")}finally{setBusy(false)}}return <AuthShell><form onSubmit={submit} className="space-y-4"><div><label className="text-sm font-medium" htmlFor="admin-username">Usuário</label><Input id="admin-username" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} className="mt-1" required/></div><div><label className="text-sm font-medium" htmlFor="admin-password">Senha</label><Input id="admin-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1" required/></div>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button type="submit" disabled={busy||!username||!password} className="w-full bg-[#0b2343]">{busy?"Entrando...":"Entrar"}</Button></form></AuthShell>}
function ChangePassword({username,onChanged}:{username:string;onChanged:()=>void}){const[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();if(password!==confirm){setError("As senhas não coincidem.");return}setBusy(true);setError("");try{await changeAdminPassword(password);onChanged();toast.success("Senha atualizada") }catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível alterar a senha.")}finally{setBusy(false)}}return <AuthShell><form onSubmit={submit} className="space-y-4"><div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800"><b>{username}</b>, crie uma nova senha antes de continuar.</div><div><label className="text-sm font-medium" htmlFor="new-password">Nova senha</label><Input id="new-password" type="password" autoComplete="new-password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1" required/></div><div><label className="text-sm font-medium" htmlFor="confirm-password">Confirmar senha</label><Input id="confirm-password" type="password" autoComplete="new-password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1" required/></div>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button type="submit" disabled={busy||password.length<8||!confirm} className="w-full bg-[#0b2343]">{busy?"Salvando...":"Salvar nova senha"}</Button></form></AuthShell>}
function AdminUsers(){const[users,setUsers]=useState<AdminUser[]>([]),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);const loadUsers=useCallback(async()=>{try{setUsers(await listAdminUsers())}catch(error){console.error(error);toast.error("Não foi possível carregar os administradores")}},[]);useEffect(()=>{void loadUsers()},[loadUsers]);async function create(e:React.FormEvent){e.preventDefault();setBusy(true);try{await createAdminUser(username,password);setUsername("");setPassword("");await loadUsers();toast.success("Administrador criado")}catch(error){console.error(error);toast.error(error instanceof Error?error.message:"Não foi possível criar o usuário")}finally{setBusy(false)}}return <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><div className="mb-2 grid size-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><UserPlus/></div><CardTitle>Novo administrador</CardTitle><CardDescription>O usuário será obrigado a trocar a senha no primeiro acesso.</CardDescription></CardHeader><CardContent><form onSubmit={create} className="space-y-4"><div><label className="text-sm font-medium" htmlFor="new-username">Usuário</label><Input id="new-username" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} minLength={3} pattern="[A-Za-z0-9._-]+" className="mt-1" required/></div><div><label className="text-sm font-medium" htmlFor="temporary-password">Senha temporária</label><Input id="temporary-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} className="mt-1" required/></div><Button type="submit" disabled={busy||username.length<3||password.length<8} className="w-full bg-[#0b2343]">{busy?"Criando...":"Criar administrador"}</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Administradores</CardTitle><CardDescription>Usuários autorizados a gerenciar conteúdos e TVs.</CardDescription></CardHeader><CardContent className="space-y-3">{users.map(user=><div key={user.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><div className="grid size-10 place-items-center rounded-xl bg-slate-100"><KeyRound className="size-4"/></div><div className="flex-1"><p className="font-semibold">{user.username}</p><p className="text-xs text-slate-500">Criado em {new Date(user.createdAt).toLocaleDateString("pt-BR")}</p></div><Badge className={user.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}>{user.active?"Ativo":"Inativo"}</Badge></div>)}</CardContent></Card></div>}
function TopButton({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <Button onClick={onClick} className="bg-[#0b2343] hover:bg-[#102f58]"><Plus/>{children}</Button>}
function Overview({data,loading,online,storage,jump}:{data:Data;loading:boolean;online:number;storage:number;jump:(s:string,m?:any)=>void}){const stats=[["TVs cadastradas",data.tvs.length,Monitor,"text-blue-600","bg-blue-50"],["TVs online",online,Wifi,"text-emerald-600","bg-emerald-50"],["Conteúdos ativos",data.media.length,Film,"text-violet-600","bg-violet-50"],["Armazenamento",bytes(storage),HardDrive,"text-amber-600","bg-amber-50"]] as const;return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([l,v,Icon,c,b])=><Card key={l} className="gap-3 border-slate-200/80 py-5 shadow-[0_8px_30px_rgba(15,23,42,.04)]"><CardContent className="flex items-center gap-4 px-5"><div className={`grid size-12 place-items-center rounded-2xl ${b} ${c}`}><Icon className="size-5"/></div><div><p className="text-sm text-slate-500">{l}</p><p className="mt-1 text-2xl font-bold text-slate-950">{loading?"—":v}</p></div></CardContent></Card>)}</div>
 <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Card className="border-0 bg-gradient-to-br from-[#0b2343] via-[#0d2b51] to-[#11416a] text-white shadow-xl"><CardHeader><div className="flex justify-between"><div><CardTitle className="text-xl">Coloque sua comunicação no ar</CardTitle><CardDescription className="mt-2 text-slate-300">Envie conteúdos em alta qualidade, monte uma playlist e vincule à primeira TV.</CardDescription></div><div className="grid size-11 place-items-center rounded-2xl bg-emerald-400 text-[#07213f]"><Zap className="size-5"/></div></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{[["1","Enviar conteúdo","contents","upload"],["2","Criar playlist","playlists","playlist"],["3","Cadastrar TV","tvs","tv"]].map(([n,l,s,m])=><button key={n} onClick={()=>jump(s,m)} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/7 p-4 text-left hover:bg-white/12"><span className="grid size-7 place-items-center rounded-lg bg-emerald-400/15 text-xs font-bold text-emerald-300">{n}</span><span className="text-sm font-medium">{l}</span><ChevronRight className="ml-auto size-4"/></button>)}</CardContent></Card><Card className="border-slate-200/80"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Activity className="size-4 text-emerald-500"/>Saúde da operação</CardTitle></CardHeader><CardContent className="space-y-4"><Health label="Players conectados" value={data.tvs.length?Math.round(online/data.tvs.length*100):0}/><Health label="Conteúdos processados" value={data.media.length?100:0}/><div className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs text-slate-500"><ShieldCheck className="size-4 text-emerald-500"/>Arquivos originais preservados</div></CardContent></Card></div>
 <Card className="border-slate-200/80"><CardHeader className="border-b"><CardTitle className="text-base">Conteúdos recentes</CardTitle><CardDescription>Últimos arquivos adicionados à biblioteca</CardDescription></CardHeader><CardContent className="p-0">{data.media.length?<div className="divide-y">{data.media.slice(0,5).map(m=><MediaRow key={m.id} item={m}/>)}</div>:<Empty icon={CloudUpload} title="Sua biblioteca está vazia" text="Adicione o primeiro vídeo, imagem ou anúncio para começar." action="Adicionar conteúdo" onAction={()=>jump("contents","upload")}/>}</CardContent></Card></div>}
function Health({label,value}:{label:string;value:number}){return <div><div className="mb-2 flex justify-between text-sm"><span className="text-slate-600">{label}</span><b>{value}%</b></div><Progress value={value} className="h-2 bg-slate-100 [&_[data-slot=progress-indicator]]:bg-emerald-500"/></div>}
function MediaRow({item}:{item:Media}){const Icon=item.mimeType.startsWith("video")?Film:FileImage;return <div className="flex items-center gap-3 px-5 py-4"><div className="grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-600"><Icon className="size-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.name}</p><p className="text-xs text-slate-500">{item.category} · {bytes(item.size)}</p></div><Badge variant="secondary" className="bg-emerald-50 text-emerald-700">Pronto</Badge></div>}
function Contents({items,uploading,search,onUpload,onDelete}:{items:Media[];uploading:Record<string,number>;search:string;onUpload:(f:FileList|File[])=>void;onDelete:(id:number)=>void}){const ref=useRef<HTMLInputElement>(null);return <div className="space-y-5">{Object.entries(uploading).map(([n,p])=><Card key={n} className="gap-3 py-4"><CardContent className="px-5"><div className="mb-2 flex justify-between text-sm"><span className="truncate font-medium">Enviando {n}</span><span>{p}%</span></div><Progress value={p} className="[&_[data-slot=progress-indicator]]:bg-emerald-500"/></CardContent></Card>)}<div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onUpload(e.dataTransfer.files)}} className="flex min-h-40 flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-300 bg-white p-6 text-center hover:border-emerald-400"><div className="mb-3 grid size-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><CloudUpload/></div><p className="font-semibold">Arraste arquivos para enviar</p><p className="mt-1 text-sm text-slate-500">Vídeos e imagens em alta resolução, sem redução do original.</p><input ref={ref} type="file" multiple accept="video/*,image/*" className="hidden" onChange={e=>e.target.files&&onUpload(e.target.files)}/><Button variant="outline" className="mt-4" onClick={()=>ref.current?.click()}>Selecionar arquivos</Button></div>{items.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{items.map(m=><Card key={m.id} className="group gap-0 overflow-hidden border-slate-200 py-0"><div className="relative aspect-video overflow-hidden bg-[#0b2343]"><MediaPreview item={m}/><button onClick={()=>onDelete(m.id)} className="absolute right-3 top-3 grid size-8 place-items-center rounded-lg bg-black/55 text-white opacity-0 group-hover:opacity-100" aria-label="Remover"><X className="size-4"/></button></div><CardContent className="p-4"><p className="truncate font-semibold">{m.name}</p><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{m.category}</span><span>{bytes(m.size)}</span></div></CardContent></Card>)}</div>:<Empty icon={search?Search:FolderOpen} title={search?"Nenhum resultado":"Nenhum conteúdo adicionado"} text={search?"Tente buscar por outro nome.":"Envie vídeos e imagens para montar suas programações."}/>}</div>}
function MediaPreview({item}:{item:Media}){return item.mimeType.startsWith("image")&&item.url?<img src={item.url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center bg-[radial-gradient(circle_at_30%_30%,#1d5d8f,#08192d_70%)] text-white"><div className="grid size-12 place-items-center rounded-full bg-white/12"><Film/></div></div>}
function Playlists({items,onCreate}:{items:Playlist[];onCreate:()=>void}){return items.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(p=><Card key={p.id}><CardHeader><div className="mb-3 flex justify-between"><div className="grid size-11 place-items-center rounded-2xl bg-violet-50 text-violet-600"><ListVideo/></div><Badge className="bg-emerald-50 text-emerald-700">Ativa</Badge></div><CardTitle>{p.name}</CardTitle><CardDescription>{p.itemCount} conteúdos</CardDescription></CardHeader><CardContent><Button variant="outline" className="w-full">Gerenciar playlist</Button></CardContent></Card>)}</div>:<Empty icon={ListVideo} title="Nenhuma playlist criada" text="Combine seus conteúdos em uma sequência contínua." action="Criar primeira playlist" onAction={onCreate}/>}
function Schedules({items,playlists,onCreate}:{items:Schedule[];playlists:Playlist[];onCreate:()=>void}){return items.length?<div className="space-y-3">{items.map(s=><Card key={s.id} className="gap-0 py-0"><CardContent className="flex items-center gap-4 p-5"><div className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><CalendarClock/></div><div className="flex-1"><p className="font-semibold">{s.name}</p><p className="text-sm text-slate-500">{new Date(s.startsAt).toLocaleString("pt-BR")}</p></div><Badge variant="secondary">Agendada</Badge></CardContent></Card>)}</div>:<Empty icon={CalendarClock} title="Nenhuma programação" text={playlists.length?"Defina data e horário para colocar uma playlist no ar.":"Crie uma playlist antes de programar a exibição."} action={playlists.length?"Criar programação":undefined} onAction={onCreate}/>}
function Devices({items,playlists,onCreate,onPlaylistChange}:{items:Device[];playlists:Playlist[];onCreate:()=>void;onPlaylistChange:(id:number,playlistId:number|null)=>Promise<void>}){return items.length?<div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{items.map(t=><Card key={t.id}><CardHeader><div className="flex justify-between"><div className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Monitor/></div><Badge className={t.status==="online"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}>{t.status==="online"?<Wifi className="mr-1 size-3"/>:<WifiOff className="mr-1 size-3"/>}{t.status==="online"?"Online":"Offline"}</Badge></div><CardTitle className="mt-2">{t.name}</CardTitle><CardDescription>{t.unit}{t.location?` · ${t.location}`:""}</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm"><div><span className="block text-xs text-slate-500">Código</span><b className="font-mono">{t.code}</b></div><div><span className="block text-xs text-slate-500">Resolução</span><b>{t.resolution}</b></div></div><Select value={t.playlistId?String(t.playlistId):"none"} onValueChange={v=>void onPlaylistChange(t.id,v==="none"?null:Number(v))}><SelectTrigger className="w-full"><SelectValue placeholder="Vincular playlist"/></SelectTrigger><SelectContent><SelectItem value="none">Sem playlist</SelectItem>{playlists.map(p=><SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>)}</SelectContent></Select><a href={`/tv?code=${t.code}`} target="_blank"><Button variant="outline" className="w-full">Abrir player</Button></a></CardContent></Card>)}</div>:<Empty icon={Monitor} title="Nenhuma TV cadastrada" text="Cadastre um dispositivo e use o código de vinculação no player." action="Cadastrar primeira TV" onAction={onCreate}/>}
function ComingSoon({section}:{section:string}){const Icon=nav.find(n=>n[0]===section)?.[2]||Settings;return <Empty icon={Icon} title={`${titles[section][0]} pronta para configurar`} text="Este módulo faz parte da estrutura do painel e será ativado com as configurações da empresa."/>}
function Empty({icon:Icon,title,text,action,onAction}:{icon:any;title:string;text:string;action?:string;onAction?:()=>void}){return <div className="flex min-h-72 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><div className="mb-4 grid size-14 place-items-center rounded-2xl bg-slate-100 text-slate-500"><Icon/></div><h3 className="font-semibold">{title}</h3><p className="mt-1 max-w-md text-sm text-slate-500">{text}</p>{action&&<Button onClick={onAction} className="mt-5 bg-[#0b2343]"><Plus/>{action}</Button>}</div>}
function UploadDialog({open,close,onUpload}:{open:boolean;close:()=>void;onUpload:(f:FileList)=>void}){return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Adicionar conteúdo</DialogTitle><DialogDescription>O arquivo original será preservado.</DialogDescription></DialogHeader><label className="grid min-h-44 cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-slate-300 p-6 text-center hover:border-emerald-400"><div><CloudUpload className="mx-auto mb-3 text-emerald-600"/><p className="font-semibold">Clique para selecionar</p><p className="text-sm text-slate-500">Vídeos e imagens em alta qualidade</p></div><input type="file" multiple accept="video/*,image/*" className="hidden" onChange={e=>e.target.files&&onUpload(e.target.files)}/></label></DialogContent></Dialog>}
function TvDialog({open,close,playlists,onSave}:{open:boolean;close:()=>void;playlists:Playlist[];onSave:(p:any)=>Promise<void>}){const[f,setF]=useState({name:"",code:"",unit:"Matriz",location:"",resolution:"1920x1080",playlistId:""});return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Cadastrar nova TV</DialogTitle><DialogDescription>Use o código exibido no player.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="Nome da TV" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><Input placeholder="Código (SDE-001)" value={f.code} onChange={e=>setF({...f,code:e.target.value.toUpperCase()})}/><Input placeholder="Unidade" value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}/><Input placeholder="Localização" value={f.location} onChange={e=>setF({...f,location:e.target.value})}/><Select value={f.resolution} onValueChange={v=>setF({...f,resolution:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1920x1080">Full HD</SelectItem><SelectItem value="3840x2160">4K</SelectItem><SelectItem value="1080x1920">Vertical Full HD</SelectItem></SelectContent></Select><Select value={f.playlistId} onValueChange={v=>setF({...f,playlistId:v})}><SelectTrigger><SelectValue placeholder="Playlist (opcional)"/></SelectTrigger><SelectContent>{playlists.map(p=><SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>)}</SelectContent></Select></div><DialogFooter><Button variant="outline" onClick={close}>Cancelar</Button><Button className="bg-[#0b2343]" onClick={()=>void onSave(f)}>Cadastrar TV</Button></DialogFooter></DialogContent></Dialog>}
function PlaylistDialog({open,close,media,onSave}:{open:boolean;close:()=>void;media:Media[];onSave:(p:any)=>Promise<void>}){const[name,setName]=useState(""),[selected,setSelected]=useState<number[]>([]);return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Criar playlist</DialogTitle><DialogDescription>Escolha os conteúdos na ordem de exibição.</DialogDescription></DialogHeader><Input placeholder="Nome da playlist" value={name} onChange={e=>setName(e.target.value)}/><div className="max-h-72 space-y-2 overflow-auto">{media.length?media.map(m=><button key={m.id} onClick={()=>setSelected(v=>v.includes(m.id)?v.filter(id=>id!==m.id):[...v,m.id])} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected.includes(m.id)?"border-emerald-400 bg-emerald-50":"border-slate-200"}`}><div className="grid size-9 place-items-center rounded-lg bg-slate-100">{m.mimeType.startsWith("video")?<Film className="size-4"/>:<FileImage className="size-4"/>}</div><span className="min-w-0 flex-1 truncate text-sm font-medium">{m.name}</span>{selected.includes(m.id)&&<CheckCircle2 className="size-5 text-emerald-600"/>}</button>):<p className="rounded-xl bg-slate-50 p-4 text-center text-sm text-slate-500">Adicione conteúdos primeiro.</p>}</div><DialogFooter><Button variant="outline" onClick={close}>Cancelar</Button><Button disabled={!name||!selected.length} className="bg-[#0b2343]" onClick={()=>void onSave({name,mediaIds:selected})}>Criar playlist</Button></DialogFooter></DialogContent></Dialog>}
function ScheduleDialog({open,close,playlists,onSave}:{open:boolean;close:()=>void;playlists:Playlist[];onSave:(p:any)=>Promise<void>}){const[f,setF]=useState({name:"",playlistId:"",startsAt:"",endsAt:""});return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Criar programação</DialogTitle><DialogDescription>Escolha a playlist e o período.</DialogDescription></DialogHeader><div className="space-y-3"><Input placeholder="Nome da programação" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><Select value={f.playlistId} onValueChange={v=>setF({...f,playlistId:v})}><SelectTrigger><SelectValue placeholder="Selecionar playlist"/></SelectTrigger><SelectContent>{playlists.map(p=><SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>)}</SelectContent></Select><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm text-slate-600">Início<Input className="mt-1" type="datetime-local" value={f.startsAt} onChange={e=>setF({...f,startsAt:e.target.value})}/></label><label className="text-sm text-slate-600">Fim<Input className="mt-1" type="datetime-local" value={f.endsAt} onChange={e=>setF({...f,endsAt:e.target.value})}/></label></div></div><DialogFooter><Button variant="outline" onClick={close}>Cancelar</Button><Button disabled={!f.name||!f.playlistId||!f.startsAt} className="bg-[#0b2343]" onClick={()=>void onSave(f)}>Salvar programação</Button></DialogFooter></DialogContent></Dialog>}
