"use client";

import { useEffect, useState } from "react";
import { Maximize, Monitor, RefreshCw, Tv } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getMediaUrl, loadLocalData } from "@/lib/local-data";

type Item={id:number;name:string;mimeType:string;duration:number;url:string};
type PlayerData={paired:boolean;code?:string;tv?:{name:string;code:string};playlist?:{name:string};items?:Item[]};

export default function Player(){
 const [data,setData]=useState<PlayerData|null>(null),[index,setIndex]=useState(0),[code,setCode]=useState(""),[mediaUrl,setMediaUrl]=useState("");
 useEffect(()=>{const value=new URLSearchParams(location.search).get("code")||localStorage.getItem("tv-code")||"";setCode(value)},[]);
 useEffect(()=>{if(!code)return;localStorage.setItem("tv-code",code);const load=()=>{const all=loadLocalData();const tv=all.tvs.find((t:any)=>t.code===code.toUpperCase());if(!tv){setData({paired:false,code});return}const playlist=all.playlists.find((p:any)=>p.id===tv.playlistId);const items=(playlist?.mediaIds||[]).map((id:number)=>all.media.find((m:any)=>m.id===id)).filter(Boolean).map((m:any)=>({...m,duration:10,url:""}));setData({paired:true,tv,playlist,items})};load();window.addEventListener("tv-data-changed",load);return()=>window.removeEventListener("tv-data-changed",load)},[code]);
 const item=data?.items?.[index];
 useEffect(()=>{let active=true;if(!item){setMediaUrl("");return}void getMediaUrl(item.id).then(v=>active&&setMediaUrl(v));return()=>{active=false;if(mediaUrl)URL.revokeObjectURL(mediaUrl)}},[item?.id]);
 useEffect(()=>{if(!item||item.mimeType.startsWith("video"))return;const t=setTimeout(()=>setIndex(i=>(i+1)%(data?.items?.length||1)),(item.duration||10)*1000);return()=>clearTimeout(t)},[item,data?.items?.length]);
 const next=()=>setIndex(i=>(i+1)%(data?.items?.length||1));
 const fullscreen=()=>document.documentElement.requestFullscreen?.();
 if(!code)return <div className="grid min-h-screen place-items-center bg-[#061427] p-6 text-white"><div className="w-full max-w-md text-center"><div className="mx-auto mb-6 grid size-20 place-items-center rounded-3xl bg-emerald-400 text-[#061427]"><Tv className="size-10"/></div><h1 className="text-3xl font-bold">Vincular esta TV</h1><p className="mt-2 text-slate-400">Digite o mesmo código cadastrado no painel administrativo.</p><div className="mt-8 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="EX.: SDE-001" className="h-12 flex-1 rounded-xl border border-white/15 bg-white/8 px-4 text-center font-mono text-lg uppercase outline-none focus:border-emerald-400"/><Button onClick={()=>setCode(code.trim())} className="h-12 bg-emerald-400 text-[#061427] hover:bg-emerald-300">Vincular</Button></div></div></div>;
 if(!data)return <div className="grid min-h-screen place-items-center bg-[#061427] text-white"><RefreshCw className="size-9 animate-spin text-emerald-400"/></div>;
 if(!data.paired)return <div className="grid min-h-screen place-items-center bg-[#061427] p-6 text-white"><div className="text-center"><Monitor className="mx-auto mb-5 size-14 text-amber-400"/><h1 className="text-2xl font-bold">TV aguardando cadastro</h1><p className="mt-2 text-slate-400">Cadastre o código abaixo no painel.</p><div className="mt-6 rounded-2xl border border-white/10 bg-white/8 px-8 py-5 font-mono text-3xl font-bold tracking-widest">{code}</div><button onClick={()=>{localStorage.removeItem("tv-code");setCode("")}} className="mt-5 text-sm text-slate-400 underline">Usar outro código</button></div></div>;
 if(!item)return <div className="relative grid min-h-screen place-items-center overflow-hidden bg-[#061427] p-6 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_20%,rgba(52,211,153,.15),transparent_45%)]"/><div className="relative text-center"><div className="mx-auto mb-6 grid size-20 place-items-center rounded-3xl border border-white/10 bg-white/5"><Tv className="size-9 text-emerald-400"/></div><h1 className="text-3xl font-bold">{data.tv?.name}</h1><p className="mt-2 text-slate-400">Nenhuma playlist com conteúdo foi atribuída a esta TV.</p><p className="mt-6 font-mono text-sm text-emerald-300">{data.tv?.code}</p></div></div>;
 return <main className="group fixed inset-0 cursor-none overflow-hidden bg-black" onDoubleClick={fullscreen}>{item.mimeType.startsWith("video")?<video key={item.id} src={mediaUrl} autoPlay playsInline className="h-full w-full object-contain" onEnded={next} onError={next}/>:<img key={item.id} src={mediaUrl} alt="" className="h-full w-full object-contain"/>}<div className="pointer-events-none absolute inset-x-0 top-0 flex items-center justify-between bg-gradient-to-b from-black/55 to-transparent p-5 opacity-0 transition group-hover:opacity-100"><div className="flex items-center gap-3 text-white"><div className="grid size-9 place-items-center rounded-xl bg-emerald-400 text-[#061427]"><Tv className="size-4"/></div><div><p className="text-sm font-semibold">{data.tv?.name}</p><p className="text-xs text-white/60">{data.playlist?.name}</p></div></div><button onClick={fullscreen} className="pointer-events-auto grid size-10 cursor-pointer place-items-center rounded-xl bg-black/35 text-white"><Maximize className="size-5"/></button></div></main>
}
