create extension if not exists pgcrypto;

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  name text not null,
  mime_type text not null,
  size bigint not null default 0,
  category text not null default 'Geral',
  status text not null default 'ready',
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id bigint not null references public.playlists(id) on delete cascade,
  media_id bigint not null references public.media(id) on delete cascade,
  position integer not null default 0,
  unique (playlist_id, media_id)
);

create table if not exists public.tvs (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  unit text not null default 'Matriz',
  location text not null default '',
  resolution text not null default '1920x1080',
  orientation text not null default 'horizontal',
  status text not null default 'offline',
  playlist_id bigint references public.playlists(id) on delete set null,
  last_seen timestamptz,
  public_token uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now()
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  name text not null,
  playlist_id bigint not null references public.playlists(id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'scheduled',
  created_at timestamptz not null default now()
);

alter table public.media enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_items enable row level security;
alter table public.tvs enable row level security;
alter table public.schedules enable row level security;

drop policy if exists "Public read media" on public.media;
create policy "Public read media" on public.media for select using (true);
drop policy if exists "Public write media" on public.media;
create policy "Public write media" on public.media for all using (true) with check (true);

drop policy if exists "Public read playlists" on public.playlists;
create policy "Public read playlists" on public.playlists for select using (true);
drop policy if exists "Public write playlists" on public.playlists;
create policy "Public write playlists" on public.playlists for all using (true) with check (true);

drop policy if exists "Public read playlist items" on public.playlist_items;
create policy "Public read playlist items" on public.playlist_items for select using (true);
drop policy if exists "Public write playlist items" on public.playlist_items;
create policy "Public write playlist items" on public.playlist_items for all using (true) with check (true);

drop policy if exists "Public read tvs" on public.tvs;
create policy "Public read tvs" on public.tvs for select using (true);
drop policy if exists "Public write tvs" on public.tvs;
create policy "Public write tvs" on public.tvs for all using (true) with check (true);

drop policy if exists "Public read schedules" on public.schedules;
create policy "Public read schedules" on public.schedules for select using (true);
drop policy if exists "Public write schedules" on public.schedules;
create policy "Public write schedules" on public.schedules for all using (true) with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('tv-media', 'tv-media', true, 52428800, array['video/mp4','video/webm','video/quicktime','image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read TV media" on storage.objects;
create policy "Public read TV media" on storage.objects for select using (bucket_id = 'tv-media');
drop policy if exists "Public upload TV media" on storage.objects;
create policy "Public upload TV media" on storage.objects for insert with check (bucket_id = 'tv-media');
drop policy if exists "Public delete TV media" on storage.objects;
create policy "Public delete TV media" on storage.objects for delete using (bucket_id = 'tv-media');

do $$
begin
  alter publication supabase_realtime add table public.media, public.playlists, public.playlist_items, public.tvs, public.schedules;
exception when duplicate_object then null;
end $$;
